pipelines:
  branches:
    master:
      - step:
          name: Build and Test Java Solution
          image: maven:3-jdk-11
          script:
            - cd $JAVA_DIR
            - bash ./gradlew clean build
            - bash ./gradlew assemble
            - cd ..
      - step:
          name: Build and Test .NET Solution
          caches: 
            - dotnetcore
          image: mcr.microsoft.com/dotnet/core/sdk:3.1
          script:
            - dotnet restore $DOTNET_PROJ
            - dotnet publish -c release -o ./$DOTNET_DIR/build_output $DOTNET_PROJ
      # - step:
      #     name: Build and Test JavaScript Solution
      #     image: 
      #     script:
    java/*:
      - step:
          name: Build and Test Java Solution
          image: java:11
          script:
            # - echo "Starting Sonar"
            # - ./sonarqube-7.1/bin/linux-x86-64/sonar.sh start -Dsonar.branch=$BITBUCKET_BRANCH
            - cd $JAVA_DIR
            - bash ./gradlew clean build
            - cd ..
            # - echo "Stopping Sonar"
            # - ./sonarqube-7.1/bin/linux-x86-64/sonar.sh stop -Dsonar.branch=$BITBUCKET_BRANCH
          # artifacts:
          #  - dist/**
          #  - reports/*.txt
          #  - sonarqube*/logs**
    dotnet/*:
      - step:
          name: Build and Test .NET Solution
          caches: 
            - dotnetcore
          image: mcr.microsoft.com/dotnet/core/sdk:3.1
          script:
            - dotnet restore $DOTNET_PROJ
            - dotnet publish -c release -o ./$DOTNET_DIR/build_output $DOTNET_PROJ
    # javascript/*:
    #   - step:
    #       name: Build and Test JavaScript Solution
    #       image:
    #       script: