pipelines:
  branches:
    master:
      - step:
          name: Build and Test Java Solution
          image: maven:3-jdk-11
          script:
            - cd $JAVA_DIR
            - bash ./gradlew clean build
            - bash ./gradlew assemble
            - cd ..
      - step:
          name: Build and Test .NET Solution
          caches: 
            - dotnetcore
          image: mcr.microsoft.com/dotnet/core/sdk:3.1
          script:
            - dotnet restore $DOTNET_PROJ
            - dotnet publish -c release -o ./$DOTNET_DIR/build_output $DOTNET_PROJ
      # - step:
      #     name: Build and Test JavaScript Solution
      #     image: 
      #     script:
    java/*:
      - step:
          name: Build and Test Java Solution
          image: maven:3-jdk-11
          caches:
            sonar: ~/.sonar/cache
          script:
            - cd $JAVA_DIR
            - pipe: sonarsource/sonarcloud-scan:1.0.1
            #   variables:
            #     EXTRA_ARGS: -Dsonar.projectDescription=\"Project with sonarcloud-scan pipe\" -Dsonar.eslint.reportPaths=\"report.txt\"
            #     SONAR_SCANNER_OPTS: -Xmx512m
            #     DEBUG: "true"
            #     SONAR__TOKEN: ${SONAR_TOKEN}
            - bash ./gradlew clean build
            - cd ..
          artifacts:
           - dist/**
           - reports/*.txt
           - sonarqube*/logs**
    dotnet/*:
      - step:
          name: Build and Test .NET Solution
          caches: 
            - dotnetcore
          image: mcr.microsoft.com/dotnet/core/sdk:3.1
          caches:
            sonar: ~/.sonar/cache
          script:
            # - pipe: sonarsource/sonarcloud-scan:1.0.1
            #     variables:
            #       EXTRA_ARGS: -Dsonar.projectDescription=\"Project with sonarcloud-scan pipe\" -Dsonar.eslint.reportPaths=\"report.txt\"
            #       SONAR_SCANNER_OPTS: -Xmx512m
            #       DEBUG: "true"
            #       SONAR__TOKEN: ${SONAR_TOKEN}
            - dotnet restore $DOTNET_PROJ
            - dotnet publish -c release -o ./$DOTNET_DIR/build_output $DOTNET_PROJ
    # javascript/*:
    #   - step:
    #       name: Build and Test JavaScript Solution
    #       image:
    #       script: