pipelines:
  branches:
    master:
      - step:
          name: Build and Test Java Solution
          image: java:8
          script:
            - cd $JAVA_DIR
            - bash ./gradlew clean build
            - bash ./gradlew assemble
            - cd ..
      - step:
          name: Build and Test .NET Solution
          caches: 
            - dotnetcore
          image: mcr.microsoft.com/dotnet/core/sdk:3.1
          script:
            - dotnet restore $DOTNET_PROJ
            - dotnet publish -c release -o ./$DOTNET_DIR/build_output $DOTNET_PROJ
    java/*:
      - step:
          name: Build and Test Java Solution
          image: java:8
          script:
            - echo "Starting Sonar"
            - ./sonarqube-8.2.0.32929/bin/linux-x86-64/sonar.sh start -Dsonar.host.url=http://localhost:9000/ -Dsonar.branch=$BITBUCKET_BRANCH
            - cd $JAVA_DIR
            - bash ./gradlew clean build
            - cd ..
            - echo "Stopping Sonar"
            - ./sonarqube-8.2.0.32929/bin/linux-x86-64/sonar.sh stop -Dsonar.host.url=http://localhost:9000/ -Dsonar.branch=$BITBUCKET_BRANCH
    dotnet/*:
      - step:
          name: Build and Test .NET Solution
          caches: 
            - dotnetcore
          image: mcr.microsoft.com/dotnet/core/sdk:3.1
          script:
            - dotnet restore $DOTNET_PROJ
            - dotnet publish -c release -o ./$DOTNET_DIR/build_output $DOTNET_PROJ